#spring.application.name=bootProj04-otel-grafana-prometheus
spring:
  application:
    name: bootProj04-otel-grafana-prometheus

management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - metrics
          - prometheus
  otlp:
    metrics:
      export:
        url: http://localhost:4318/v1/metrics
        step: 10s
    tracing:
      endpoint: http://localhost:4318/v1/traces
      export:
        step: 10s #Export interval set to 10s
  tracing:
    sampling:
      probability: 1.0

